name: NMLAcrobatics
version: '1.0'
main: io.github.NoOne.nMLAcrobatics.NMLAcrobatics
api-version: '1.21'
depend:
  - NMLSkills
commands:
  setyawandpitch:
    description: Sets your yaw and pitch
    usage: /setyawandpitch <yaw> <pitch>